// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.maxhanchen.dao.po;

import com.maxhanchen.dao.po.FrontUser;
import com.maxhanchen.dao.po.Order;
import com.maxhanchen.dao.po.OrderDataOnDemand;
import com.maxhanchen.dao.service.OrderService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrderDataOnDemand: @Component;
    
    private Random OrderDataOnDemand.rnd = new SecureRandom();
    
    private List<Order> OrderDataOnDemand.data;
    
    @Autowired
    OrderService OrderDataOnDemand.orderService;
    
    public Order OrderDataOnDemand.getNewTransientOrder(int index) {
        Order obj = new Order();
        setCreateBy(obj, index);
        setCreateTime(obj, index);
        setMessage(obj, index);
        setOrderID(obj, index);
        setOrderName(obj, index);
        setUpdateBy(obj, index);
        setUpdateTime(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void OrderDataOnDemand.setCreateBy(Order obj, int index) {
        String createBy = "createBy_" + index;
        obj.setCreateBy(createBy);
    }
    
    public void OrderDataOnDemand.setCreateTime(Order obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void OrderDataOnDemand.setMessage(Order obj, int index) {
        String message = "message_" + index;
        if (message.length() > 1000) {
            message = message.substring(0, 1000);
        }
        obj.setMessage(message);
    }
    
    public void OrderDataOnDemand.setOrderID(Order obj, int index) {
        Long orderID = new Integer(index).longValue();
        obj.setOrderID(orderID);
    }
    
    public void OrderDataOnDemand.setOrderName(Order obj, int index) {
        String orderName = "orderName_" + index;
        if (orderName.length() > 1000) {
            orderName = orderName.substring(0, 1000);
        }
        obj.setOrderName(orderName);
    }
    
    public void OrderDataOnDemand.setUpdateBy(Order obj, int index) {
        String updateBy = "updateBy_" + index;
        obj.setUpdateBy(updateBy);
    }
    
    public void OrderDataOnDemand.setUpdateTime(Order obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public void OrderDataOnDemand.setUsername(Order obj, int index) {
        FrontUser username = null;
        obj.setUsername(username);
    }
    
    public Order OrderDataOnDemand.getSpecificOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Order obj = data.get(index);
        Long id = obj.getId();
        return orderService.findOrder(id);
    }
    
    public Order OrderDataOnDemand.getRandomOrder() {
        init();
        Order obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return orderService.findOrder(id);
    }
    
    public boolean OrderDataOnDemand.modifyOrder(Order obj) {
        return false;
    }
    
    public void OrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = orderService.findOrderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Order' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Order>();
        for (int i = 0; i < 10; i++) {
            Order obj = getNewTransientOrder(i);
            try {
                orderService.saveOrder(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
