// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.maxhanchen.dao.po;

import com.maxhanchen.dao.po.Product;
import com.maxhanchen.dao.po.ProductDataOnDemand;
import com.maxhanchen.dao.service.ProductService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductDataOnDemand: @Component;
    
    private Random ProductDataOnDemand.rnd = new SecureRandom();
    
    private List<Product> ProductDataOnDemand.data;
    
    @Autowired
    ProductService ProductDataOnDemand.productService;
    
    public Product ProductDataOnDemand.getNewTransientProduct(int index) {
        Product obj = new Product();
        setCompany(obj, index);
        setCreateBy(obj, index);
        setCreateTime(obj, index);
        setDescription(obj, index);
        setPrice(obj, index);
        setProductName(obj, index);
        setPrudctID(obj, index);
        setTotal(obj, index);
        setUnifiedBusinessNo(obj, index);
        setUpdateBy(obj, index);
        setUpdateTime(obj, index);
        return obj;
    }
    
    public void ProductDataOnDemand.setCompany(Product obj, int index) {
        String company = "company_" + index;
        if (company.length() > 400) {
            company = company.substring(0, 400);
        }
        obj.setCompany(company);
    }
    
    public void ProductDataOnDemand.setCreateBy(Product obj, int index) {
        String createBy = "createBy_" + index;
        obj.setCreateBy(createBy);
    }
    
    public void ProductDataOnDemand.setCreateTime(Product obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void ProductDataOnDemand.setDescription(Product obj, int index) {
        String description = "description_" + index;
        if (description.length() > 400) {
            description = description.substring(0, 400);
        }
        obj.setDescription(description);
    }
    
    public void ProductDataOnDemand.setPrice(Product obj, int index) {
        Long price = new Integer(index).longValue();
        obj.setPrice(price);
    }
    
    public void ProductDataOnDemand.setProductName(Product obj, int index) {
        String productName = "productName_" + index;
        obj.setProductName(productName);
    }
    
    public void ProductDataOnDemand.setPrudctID(Product obj, int index) {
        Long prudctID = new Integer(index).longValue();
        obj.setPrudctID(prudctID);
    }
    
    public void ProductDataOnDemand.setTotal(Product obj, int index) {
        Long total = new Integer(index).longValue();
        obj.setTotal(total);
    }
    
    public void ProductDataOnDemand.setUnifiedBusinessNo(Product obj, int index) {
        String unifiedBusinessNo = "unifiedBusinessNo_" + index;
        if (unifiedBusinessNo.length() > 400) {
            unifiedBusinessNo = unifiedBusinessNo.substring(0, 400);
        }
        obj.setUnifiedBusinessNo(unifiedBusinessNo);
    }
    
    public void ProductDataOnDemand.setUpdateBy(Product obj, int index) {
        String updateBy = "updateBy_" + index;
        obj.setUpdateBy(updateBy);
    }
    
    public void ProductDataOnDemand.setUpdateTime(Product obj, int index) {
        Date updateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdateTime(updateTime);
    }
    
    public Product ProductDataOnDemand.getSpecificProduct(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Product obj = data.get(index);
        Long id = obj.getId();
        return productService.findProduct(id);
    }
    
    public Product ProductDataOnDemand.getRandomProduct() {
        init();
        Product obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return productService.findProduct(id);
    }
    
    public boolean ProductDataOnDemand.modifyProduct(Product obj) {
        return false;
    }
    
    public void ProductDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = productService.findProductEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Product' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Product>();
        for (int i = 0; i < 10; i++) {
            Product obj = getNewTransientProduct(i);
            try {
                productService.saveProduct(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
